# Generated by Django 6.0.6 on 2026-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCompanyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('root_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('primary_recipient_hr', models.CharField(max_length=255)),
                ('cc_founder', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_engineering_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_senior_dev', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location', models.TextField(blank=True, null=True)),
                ('target_tech_stack', models.CharField(max_length=255)),
                ('evidence_url_hr', models.URLField(max_length=1024)),
                ('evidence_url_cc', models.URLField(blank=True, max_length=1024, null=True)),
                ('campaign_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
