# Generated by Django 6.0.6 on 2026-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcompanycampaign',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
