# Generated by Django 6.0.6 on 2026-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_targetcompanycampaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcompanycampaign',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
