# Generated by Django 6.0.6 on 2026-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_targetcompanycampaign_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcompanycampaign',
            name='campaign_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
