# Generated by Django 6.0.6 on 2026-07-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_targetcompanycampaign_campaign_inputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_inputs',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tech',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('employees', models.CharField(blank=True, max_length=50, null=True)),
                ('founded', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hiring', models.BooleanField(default=False)),
                ('tech_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('hr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('founder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('engineering_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_contact', models.URLField(blank=True, max_length=1024, null=True)),
                ('evidence_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('verification_reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_status', models.CharField(choices=[('PENDING', 'Pending'), ('SEARCHING', 'Searching'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaigns.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='TargetCompanyCampaign',
        ),
    ]
