# Generated by Django 6.0.6 on 2026-09-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campaign_campaign_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_response_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
