# Generated by Django 6.0.6 on 2026-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_ai_response_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
