# Generated by Django 6.0.6 on 2026-09-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionledger',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionledger',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionledger',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionledger',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionledger',
            name='transaction_type',
            field=models.CharField(choices=[('SIGNUP', 'Signup Bonus'), ('EMAIL_DRAFT', 'Email Drafting'), ('REFILL', 'Manual Refill'), ('RAZORPAY', 'Razorpay Online Payment')], max_length=50),
        ),
    ]
