# Generated by Django 6.0.6 on 2026-07-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_resume_file_resume_resume_public_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
