# Generated by Django 6.0.6 on 2026-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingjob',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='processingjob',
            name='screenshot_public_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='screenshot_storage_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
