# Generated by Django 6.0.6 on 2026-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_email_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
