# Generated by Django 6.0.6 on 2026-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_custom_email_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_connected',
            field=models.BooleanField(default=False),
        ),
    ]
